### ISSUE TITLE
怎么设置cookie呀

### ISSUE THREAD

**Issue by yuanshangyujingshierlou** [Jiny3213/vscode-tieba#5]
大佬

**Comment by ifhjl** [comment]
建议有问题的话自己先百度一下，来跟我做：输入www.baidu.com，搜索：如何获取贴吧cookie，点击网页：
https://jingyan.baidu.com/article/75ab0bcb1a119396864db2e2.html
小朋友学会了吗？

**Comment by yuanshangyujingshierlou** [comment]
> 建议有问题的话自己先百度一下，来跟我做：输入www.baidu.com，搜索：如何获取贴吧cookie，点击网页： https://jingyan.baidu.com/article/75ab0bcb1a119396864db2e2.html 小朋友学会了吗？

学会了 谢谢大佬
